version: "3.3"
services:
  mongo:
    container_name: "colorizer_mongo"
    image: "mongo:latest"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
  api:
    container_name: "colorizer_api"
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 8001:8000
    links:
      - mongo
  client:
    container_name: "colorizer_client"
    build: ./client
    stdin_open: true
    volumes:
      - ./client/src:/client/src
    ports:
      - 3001:3000
    links:
      - api
