version: "3.3"

services:
  mongo:
    container_name: "colorizer_mongo"
    image: "mongo:latest"
    restart: on-failure
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
  api:
    container_name: "colorizer_api"
    build: ./api
    restart: on-failure
    volumes:
      - ./api/server:/app/server
    ports:
      - 4001:8000
    links:
      - mongo

volumes:
  colorizer-db:
